main: com.cavetale.xmas.XmasPlugin

name: Xmas
version: 0.1
description: Xmas Plugin
api-version: '1.20'

author: StarTux
website: https://github.com/StarTux/Xmas

depend: [Core, Mytems, Area, Sidebar, Resident, MagicMap, Poster]
softdepend: []

commands:

  xmas:
    aliases: []
    description: Player Command
    permission: xmas.xmas
    usage: |-
      /xmas

  xmasadmin:
    aliases: [xmasadm]
    description: Player Command
    permission: xmas.admin
    usage: |-
      /xmasadmin

permissions:

  xmas.xmas:
    description: Use /xmas
    default: op

  xmas.admin:
    description: Use /xmasadmin
    default: op

  xmas.nocooldown:
    description: Skip cooldowns
    default: false
